name: Release

on:
    push:
        branches:
            - release

jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            version: ${{ steps.set-version.outputs.VERSION }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set version
              id: set-version
              run: |
                  echo "VERSION=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_ENV
                  echo "VERSION=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT
                  echo "Version: $(date +%Y.%-m.%-d.%-H%M)"

            - name: Tag commit
              run: |
                  git tag v$VERSION ${{ github.sha }}
                  git push origin v$VERSION

    release:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{needs.version.outputs.VERSION}}
        permissions:
            contents: write
        steps:
            - name: Download all workflow run artifacts
              uses: actions/download-artifact@v3

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: "v${{env.VERSION}}"
