name: Release

on:
    workflow_dispatch:

jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            version: ${{ steps.set-version.outputs.VERSION }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set version
              id: set-version
              run: |
                  echo "VERSION=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_ENV
                  echo "VERSION=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_OUTPUT
                  echo "Version: $(date +%Y.%-m.%-d.%-H%M)"

            - name: Fetch tags
              run: git fetch --tags

            - name: Generate changelog
              id: changelog
              run: |
                  echo 'CHANGELOG=' >> $GITHUB_ENV
                  LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                  echo "CHANGELOG=$(git log $LAST_TAG..HEAD --pretty=format:"- %s ([view](https://github.com/${{ github.repository }}/commit/%H))")" >> $GITHUB_ENV

            - name: Tag commit
              run: |
                  git tag $VERSION ${{ github.sha }}
                  git push origin $VERSION

    release:
        needs: version
        runs-on: ubuntu-latest
        env:
            VERSION: ${{needs.version.outputs.VERSION}}
        permissions:
            contents: write
        steps:
            - name: Download all workflow run artifacts
              uses: actions/download-artifact@v3

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: "${{env.VERSION}}"
                  body: ${{ needs.version.outputs.changelog }}
